myPackage/models.py
# pip install flask-sqlalchemy
from myPackage import db, login_manager
from datetime import datetime
from flask_login import UserMixin

@login_manager.user_loader
def load_user(student_id):
	return Student.query.get(int(student_id))


class Student(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    name = db.Column(db.String(50), nullable=False)
    age = db.Column(db.Integer)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    profile_image = db.Column(db.String(120))
    subjects = db.relationship('Subject', backref='editor', lazy=True)
    
def __repr__(self):
		return f"Student('{self.username}', '{self.password}')"

    
class Subject(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    name = db.Column(db.String(50), nullable=False)
    content = db.Column(db.Text)
    duration = db.Column(db.Integer, nullable=False)
    student_id = db.Column(db.Integer, db.ForeignKey("student.id"), nullable=False)
    
def __repr__(self):
		return f"Post('{self.name}', '{self.duration}')"
    

myPackage/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, IntegerField, HiddenField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from myPackage.models import Student, Subject

class RegistrationForm(FlaskForm):
	username = StringField(
		'Username',
		validators=[
			DataRequired(),
			Length(min=3, max=20)
		]
	)
	email = StringField(
		'Email',
		validators=[
			DataRequired(),
			Email()
		]
	)
	password = PasswordField(
		'Password',
		validators=[
			DataRequired()
		]
	)
	confirm_password = PasswordField(
		'Confirm Password',
		validators=[
			DataRequired(),
			EqualTo('password')
		]
	)
	name = StringField(
		'Name',
		validators=[
			DataRequired(),
			Length(min=3, max=20)
		]
	)
	age = IntegerField(
			'Age',
			validators=[
				DataRequired()
			]
		)
	submit = SubmitField(
		'Sign Up'
	)


	# custom validation for duplicates
	def validate_username(self, username):
		student = Student.query.filter_by(username=username.data).first()
		if student:
			raise ValidationError('Username already exists')

	def validate_email(self, email):
		student = Student.query.filter_by(email=email.data).first()
		if student:
			raise ValidationError('Email already exists')


class LoginForm(FlaskForm):
	username  = StringField(
		'Username',
		validators=[
			DataRequired(),
			Length(min=3, max=20)
		]
	)
	password = PasswordField(
		'Password',
		validators=[
			DataRequired()
		]
	)
	submit = SubmitField(
		'Sign In'
	)
 
 
class SubjectForm(FlaskForm):
    name = StringField(
        'Name',
        validators=[
                    DataRequired(),
                    Length(min=3, max=20)
                   ]
    )
    content = TextAreaField(
        'Content',
        validators=[
                    DataRequired(),
                   ]
    )
    duration = IntegerField(
        'Duration',
        validators=[
                    DataRequired(),
                   ]
    )
    student_id = IntegerField(
		'Student ID',
        validators=[
                    DataRequired()
                   ],
        # render_kw={'readonly':True}
	)
    submit = SubmitField(
        'Submit',
    ) 

myPackage/__init__.py
# flask imports
from flask import Flask
import os

# DB Imports
from flask_sqlalchemy import SQLAlchemy

# Migration imports -> pip install Flask-Migrate
from flask_migrate import Migrate
from sqlalchemy import MetaData

# Login Imports -> pip install flask-login
from flask_login import LoginManager

# create flask app, __name__ = tell flask where to look

app = Flask (__name__)

app.config['SECRET_KEY'] =  os.environ['SECRET_KEY']

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

metadata = MetaData(naming_convention=convention)
db = SQLAlchemy(app, metadata=metadata)
# from .models import *
migrate = Migrate(app, db, render_as_batch=True)
login_manager = LoginManager(app)

from myPackage import routes
from myPackage.routes import users
app.register_blueprint(users)

myPackage/routes.py
from myPackage import * 
from flask import render_template, url_for, redirect, flash, Blueprint, session
from myPackage.forms import RegistrationForm, LoginForm, SubjectForm
from myPackage.models import Student, Subject
from flask import request
from test import create_db
from flask_login import login_user, current_user, logout_user, login_required
from flask_bcrypt import Bcrypt
bcrypt = Bcrypt()

# blueprint
users = Blueprint(
	'users',
	__name__,
	url_prefix='/users'
)

menu={
        'Home': "/home",
        'About': "/about",
        'Registration': "/user/register",
        'Login': "/user/login",
        'Subject': "/subject/add",
        'Logout':"/logout"
    }


# home routing
@app.route('/')
@app.route('/home')
def home():
    result = [
        {"student":"merna",
        "grade":"30",
        "year":1997},
        {"student":"mariam",
        "grade":"20",
        "year":1996},
        {"student":"sara",
        "grade":"50",
        "year":1995},
        ]
    
    create_db()   
    return render_template('home.html', result = result,title="Home Page", menu=menu)


# about routing
@app.route('/about')
@login_required
def about():
	return render_template('about.html', title ="About page", menu=menu)

# redirect function
@app.route('/redirect')
def redirectFun():
    return redirect(url_for('home'))


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        flash(f'Registration Successful. You can now log in. {form.username.data} , {form.password.data}", "success"')
        with app.app_context():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf8')
            new_student=Student(name=form.name.data, age=form.age.data, username=form.username.data, email=form.email.data, password=hashed_password)
            db.session.add(new_student)
            db.session.commit()
        flash(f"Registration Successful {form.username.data}", "success")
        return redirect(url_for('login'))
            
    return render_template('register.html', title='Registration Page', form=form, menu=menu)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()

    if form.validate_on_submit():        
        student = Student.query.filter_by(username=form.username.data).first()
        # if user exists , check his password
        if student and bcrypt.check_password_hash(student.password,form.password.data):
            login_user(student)
            flash(f"Login Successful {student.username}", "success")
            return redirect(url_for('home'))
        else:
            flash(f"Incorrect username or password. Please try again.", "danger")
            return render_template('login.html', title='Login Page', form=form, menu=menu)
        
    return render_template('login.html', title='Login Page', form=form, menu=menu)
        

@app.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('home'))


@app.route('/subject/add', methods=['GET', 'POST'])
def subject_add():
    form = SubjectForm()
    if form.validate_on_submit():
        # session['student_id'] = Student.id
        # current_user = Student.query.filter_by(id=session['id']).first()
        subject = Subject(name=form.name.data, content=form.content.data, duration=form.duration.data, student_id=form.student_id.data)
        db.session.add(subject)
        db.session.commit()
        flash('Subject added successfully!')
        return redirect(url_for('home'))
    
    return render_template('subjectAdd.html', form=form, menu=menu, title="Add Subject Page")

myPackage/templates/about.html
{%  extends 'layout.html' %}

{% block content %}
    <h1>About page</h1>
{% endblock %}

myPackage/templates/home.html
{%  extends 'layout.html' %}

{% block content %}
{% if result %}
    {% for element in result %}
        <h1>{{element.student}}</h1>
        <h1>{{element.grade}}</h1>
        <h1>{{element.year}}</h1>
    {% endfor %}
{% else %}
    <h1>there is no block</h1>
{% endif %}
{% endblock %}

myPackage/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% if title %}
        <title>{{title}}</title>
        {% if title=="Home Page" %}
            <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='home.css')}}">
        {% endif %}
        {% if title=="About page" %}
            <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='about.css')}}">
        {% endif %}
        {% if title=="Registration Page" %}
            <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='register.css')}}">
        {% endif %}
        {% if title=="Login Page" %}
            <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='login.css')}}">
        {% endif %}
        {% if title=="Subject Page" %}
            <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='subjectAdd.css')}}">
        {% endif %}
    {% else %}
        <title> Flask page</title>
    {% endif %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
</head>
<body>
	<div class="container">
        <!-- {% block menu %}
            <nav>
                <ul class="nav nav-tabs nav-pills nav-justified">
                    {% for tagName, link in menu.items() %}
                        <li class="nav-item"><a href="{{link}}" class="nav-link">{{tagName}}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        {% endblock %} -->

        {% block nav %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('home') }}">Logo</a>
                <div class="navbar-expand" id="navbarNav">
                    <ul class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('home') }}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('about') }}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('subject_add') }}">Add Subject</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('home') }}">Home</a>
                            </li>
                            <!-- <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('about') }}">About</a>
                            </li> -->
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                </div>
            </nav>
        {% endblock %}

        {% with messages = get_flashed_messages(with_categories=True) %}
			{% if messages %}
				{% for category,message in messages %}
					<div class="alert alert-{{ category }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
		{% endwith %}


        {% block content %}
                    
        {% endblock %}

	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

myPackage/templates/login.html
{% extends "layout.html" %}

{% block content %}
<h1>Login Page</h1>
<div>
	<!-- post on the same route with empty action -->
	<form action="" method="POST">
		<!-- hidden tag is like csrf token for protection -->
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}
				{{ form.username(class="form-control") }}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{{ form.password(class="form-control") }}
			</div>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-primary") }}
			</div>
		</fieldset>
	</form>
</div>
{% endblock %}

myPackage/templates/register.html
{% extends "layout.html" %}

{% block content %}
<h1>Registration Page</h1>
<div>
	<!-- post on the same route with empty action -->
	<form action="" method="POST">
		<!-- hidden tag is like csrf token for protection -->
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<div class="form-group">
				{{ form.name.label(class="form-control-label") }}

				<!-- if data not valid , display errors -->
				{% if form.name.errors %}
					{{ form.name(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.name.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.name(class="form-control") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.age.label(class="form-control-label") }}

				<!-- if data not valid , display errors -->
				{% if form.age.errors %}
					{{ form.age(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.age.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.age(class="form-control") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}

				<!-- if data not valid , display errors -->
				{% if form.username.errors %}
					{{ form.username(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.username(class="form-control") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }}

				<!-- if data not valid , display errors -->
				{% if form.email.errors %}
					{{ form.email(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.email(class="form-control") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}

				<!-- if data not valid , display errors -->
				{% if form.password.errors %}
					{{ form.password(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.password.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.password(class="form-control") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.confirm_password.label(class="form-control-label") }}

				<!-- if data not valid , display errors -->
				{% if form.confirm_password.errors %}
					{{ form.confirm_password(class="form-control is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.confirm_password.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.confirm_password(class="form-control") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</fieldset>
	</form>
</div>
{% endblock %}

myPackage/templates/subjectAdd.html
{%  extends 'layout.html' %}

{% block content %}
    <h1>Add Subject Page</h1>
    <form class="form-group" action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.student_id.label() }}
            {{ form.student_id(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.name.label() }}
            {{ form.name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.content.label() }}
            {{ form.content(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.duration.label() }}
            {{ form.duration(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <!-- <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                <label class="form-label">Select Student</label>
                <select class="form-select" name="student" multiple data-mdb-clear-button="true">
                    {% for student in studentsObj %}
                        <option value="{{student.id}}" data-mdb-secondary-text="{{student.name}}">{{student.name}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                {{form.name.label(class = "form-control-label")}}

                {% if form.name.errors %}
                    {{form.name(class = "form-control is-invalid" )}}
                    {% for error in form.name.errors %}
                        <span style="color:red">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{form.name(class = 'form-control')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.content.label(class = "form-control-label")}}
                {% if form.content.errors %}
                    {{form.content(class = "form-control is-invalid" )}}
                    {% for error in form.content.errors %}
                        <span style="color:red">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{form.content(class = 'form-control')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.duration.label(class = "form-control-label")}}
                {% if form.duration.errors %}
                    {{form.duration(class = "form-control is-invalid" )}}
                    {% for error in form.duration.errors %}
                        <span style="color:red">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{form.duration(class = 'form-control')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.submit(class="btn btn-warning")}}
            </div>
        </fieldset>
    </form> -->
{% endblock %}

myPackage/templates/test.html
{% extends "layout.html" %}
{% block content %}
	{% for element in result %}
		<a href="{{ url_for(element.url) }}">{{ element.name }}</a>
	{% endfor %}
{% endblock %}